# SAMPLE JSON file

SAMPLES_JSON: samples.json

#######################################################################################

############################# Multi-Sample processing parameters (6)######################

#######################################################################################

# whether all the samples are from the same experiment. If so, peaks from all
# all samples will be merged and a count matrix for each sample will be produced
# based on the merged peak set
batch: {{ batch }}


## if batch processing is True, when merging peaks from all samples and
## the user want to call peaks from each sample individually and merge the peaks to get
## consensus peaks , only keep
## the peaks present in at least cutoff_samples samples
consensus_peaks: {{ consensus_peaks }}
cutoff_samples: {{ cutoff_samples }}



### for multiple samples from the same experiement, do you want to get the peak set
### by calling peaks with all bam files merged. If so, set bulk_peaks to True.
### bulk_peaks and consensus_peaks are mutually exclusive.
### In case some samples are deeply sequenced and you can downsample the bam files
### to a certain number (target_reads) to get the peak set. if the sample
### has fewer than the target_reads, the original number of reads will be kept.
### peak calling will be carried out by feeding MACS2 -t sample1_downsample.bam sample2_downsample.bam
### the counting of fragments will be carried out using this peak set but from the original
### un-downsampled fragment files.
bulk_peaks: {{ bulk_peaks }}
downsample: {{ downsample }}
target_reads: {{ target_reads }}




#######################################################################################

############################# Input parameters (8) ###########################

#######################################################################################

input_path: {{ input_path }}

# If the input files are gzipped
gzip: {{gzip}}

# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: {{ species }}

# Platform of single cell ATAC-seq [10x-genomics, sci-ATAC-seq, microfluidic]
platform: {{ platform }}

# The format of input files [fastq, bam, fragments]
# If the platform is 10x-genomics, users can start with sequencing fastq files, bam files with CB tag or fragments.tsv.gz file generated by CellRanger ATAC.
# If the platform is sci-ATAC-seq, users can start with sequencing fastq files, bam files with CB tag.
# If the platform is microfluidic, users can only start with sequencing fastq files.
# If the format is 'fastq', fastqdir and fastqprefix need to be set.
# If the format is 'bam', bam needs to be set.
# If the format is 'fragments', frag needs to be set.
format: {{ format }}

## select the alignmet tool for mapping
mapping: {{mapping}}

# deduplication at cell level or bulk level. "cell level" or "bulk level"
deduplication: {{ deduplication }}

#######################################################################################

############################# Reference genome parameters (3) ###########################

#######################################################################################

# Path of the giggle annotation file required for regulator identification.
# Please download the annotation file from http://cistrome.org/~galib/giggle.all.tar.gz and decompress it.
giggleannotation: {{ giggleannotation }}

# Reference genome
genome:
  # Genome fasta file for mapping. Users can just download the fasta file
  # from http://cistrome.org/~chenfei/MAESTRO/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz and decompress it.
  # For example, 'Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa'.
  #fasta: /liulab/mtang/references/Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa
  fasta: {{ fasta }}
  #If using chromap, reference index is also required
  index: {{ index }}


#######################################################################################

############################# Barcode library parameters (1) ###########################

#######################################################################################
# If the platform is 'sci-ATAC-seq' or '10x-genomics', please specify the barcode library (whitelist)
# so that the pipeline can correct cell barcodes with 1 base mismatched.
# Otherwise, the pipeline will automatically output the barcodes with enough read count (>1000).
# The 10X Chromium whitelist file can be found inside the CellRanger-ATAC distribution.
# For example, in CellRanger-ATAC 1.1.0, the whitelist is 'cellranger-atac-1.1.0/cellranger-atac-cs/1.1.0/lib/python/barcodes/737K-cratac-v1.txt'.
#whitelist: /liulab/mtang/references/cellranger-atac-1.2.0/cellranger-atac-cs/1.2.0/lib/python/barcodes/737K-cratac-v1.txt
whitelist: {{ whitelist }}


#######################################################################################

############################# Output parameters (1) ###########################

#######################################################################################
#Number of cores to use.
cores: {{ cores }}


#######################################################################################

############################# Signature files parameters (3) ###########################

#######################################################################################



# Whether or not to perform cell-type annotation.
# By default (not set), MAESTRO will skip the step of cell-type annotation.
# If set, please specify the method of cell-type annotation through method.
annotation: {{ annotation }}

# Method to annotate cell types [RP-based, peak-based, both].
# MAESTRO provides two strategies to annotate cell types for scATAC-seq data.
# Users can choose from 'RP-based' and 'peak-based', or choose to run both of them.
# One is based on gene regulatory potential predicted by RP model. Another is based on the bulk chromatin accessibility data from Cistrome database.
# If 'RP-based' is set, MAESTRO performs the cell-type annotation using the gene regulatory potential to represent gene expression,
# and the logFC of gene regulatory potential between one cluster and all the other cells is used to calculate the gene signature scores.
# If 'peak-based' is set, MAESTRO utilizes GIGGLE to evaluate the enrichment of bulk chromatin accessibility peaks on cluster-specific peaks from scATAC-seq data,
# and then transfers the Cistrome cluster identity from the most enriched bulk chromatin accessibility data as the cell-type annotation for the scATAC-seq cluster.
# See the MAESTRO paper for more details. DEFAULT: RP-based.
method: {{ method }}

# Cell signature file used to annotate cell types. MAESTRO provides several sets of built-in cell signatures.
# Users can choose from ['human.immune.CIBERSORT', 'mouce.brain.ALLEN', 'mouse.all.facs.TabulaMuris', 'mouse.all.droplet.TabulaMuris'].
# Custom cell signatures are also supported. In this situation, users need to provide the file location of cell signatures,
# and the signature file is tab-seperated without header. The first column is cell type, and the second column is signature gene.
signature: {{ signature }}


#######################################################################################

############################# Customized peak parameters (4) ###########################

#######################################################################################

# Whether or not to provide custom peaks. [False, True]
# If custompeaks is set as True, users need to provide the file location of peak file through custompeaksloc
# and then MAESTRO will merge the custom peak file and the peak file called from all fragments using MACS2.
# By default (False), the pipeline will use the peaks called using MACS2. DEFAULT: False.
custompeaks: {{ custompeaks }}

# IF custompeaks = TRUE, provide the file location of custom peaks
# The peak file is BED formatted with tab seperated.
# The first column is chromsome, the second is chromStart, and the third is chromEnd.
custompeaksloc: {{ custompeaksloc }}

# Whether or not to call peaks from short fragments (shorter than 150bp). [True, False]
# If it's set as True, MAESTRO will merge the peaks called from all fragments and those called from short fragments,
# and then use the merged peak file for further analysis.
# If not (by default), the pipeline will only use peaks called from all fragments.
shortpeaks: {{ shortpeaks }}

# Whether or not to call peaks by cluster [True, False]
# If it's set True, MAESTRO will split the fragment file according to clustering result, and then call peaks for each cluster.
# By default (not set), MAESTRO will skip this step.
clusterpeaks : {{ clusterpeaks }}

#######################################################################################

############################# Gene score parameters (6)###########################

#######################################################################################

# The RP model to use to calaculate gene score. [Simple, Enhanced ]
# For each gene, simple model sums over the impact of all regulatory elements within the up/dowm-stream of TSS.
# On the basis of simple model, Enhanced model gives the regulatory elements within the exon region a higher weight,
# and also excludes the regulatory elements overlapped with another gene (the promoter and exon of a nearby gene).
# See the MAESTRO paper for more details. DEFAULT: Enhanced.
rpmodel: {{ rpmodel }}

# Gene score decay distance, could be optional from 1kb (promoter-based regulation) and 10kb(enhancer-based regulation), default is 10kb
genedistance: {{ genedistance }}


#######################################################################################

############################# Quality control cutoff parameters ###########################

#######################################################################################

cutoff:
  # Minimum number of peaks included in each cell. DEFAULT: 100.
  peak: {{ peak }}
  # Cutoff for the number of count in each cell. DEFAULT: 1000.
  count: {{ count }}
  # Cutoff for fraction of reads in promoter in each cell. DEFAULT: 0.2.
  frip: {{ frip }}
  # Minimum number of cells covered by each peak. DEFAULT: 10.
  cell: {{ cell }}
